version: "3"
services:
  node:
    image: node
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - ../frontend/dist:/frontend/dist
    ports:
      - "3000:3000"
    depends_on:
     - mongo
    links:
      - mongo
    command: bash -c "cd app/src && node express.js"
  mongo:
    image: mongo
    volumes:
      - ./db:/data
    ports:
      - "27777:27777"
    command: "mongod --port 27777"
  mongo-restore:
    image: mongo
    volumes:
      - ./db:/data
    links:
      - mongo
    command: bash -c "mongorestore --host=mongo --port=27777 -d Tyumen ./db"
networks:
  default:
    external:
      name: nat